import Head from 'next/head'
import Homepage from '../components/Homepage/Index'

export default function Home() {
  return (
   
      <><Head>
      <title>Mind Optimizer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <Homepage />
    
    </>
    
  )
}
